version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mount local files into container for changes to be reflected during development
    ports:
      - "8000:80"  # Expose port 8080 on host
